//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.15 at 10:56:07 AM EET 
//


package com.iunona_trip.soapproducer.reservation;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.iunona_trip.soapproducer.reservation package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.iunona_trip.soapproducer.reservation
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRQ }
     * 
     */
    public OTAHotelResNotifRQ createOTAHotelResNotifRQ() {
        return new OTAHotelResNotifRQ();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRS }
     * 
     */
    public OTAHotelResNotifRS createOTAHotelResNotifRS() {
        return new OTAHotelResNotifRS();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRS.HotelReservations }
     * 
     */
    public OTAHotelResNotifRS.HotelReservations createOTAHotelResNotifRSHotelReservations() {
        return new OTAHotelResNotifRS.HotelReservations();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRS.HotelReservations.HotelReservation }
     * 
     */
    public OTAHotelResNotifRS.HotelReservations.HotelReservation createOTAHotelResNotifRSHotelReservationsHotelReservation() {
        return new OTAHotelResNotifRS.HotelReservations.HotelReservation();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRS.HotelReservations.HotelReservation.ResGlobalInfo }
     * 
     */
    public OTAHotelResNotifRS.HotelReservations.HotelReservation.ResGlobalInfo createOTAHotelResNotifRSHotelReservationsHotelReservationResGlobalInfo() {
        return new OTAHotelResNotifRS.HotelReservations.HotelReservation.ResGlobalInfo();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRS.HotelReservations.HotelReservation.ResGlobalInfo.HotelReservationIDs }
     * 
     */
    public OTAHotelResNotifRS.HotelReservations.HotelReservation.ResGlobalInfo.HotelReservationIDs createOTAHotelResNotifRSHotelReservationsHotelReservationResGlobalInfoHotelReservationIDs() {
        return new OTAHotelResNotifRS.HotelReservations.HotelReservation.ResGlobalInfo.HotelReservationIDs();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRQ.HotelReservations }
     * 
     */
    public OTAHotelResNotifRQ.HotelReservations createOTAHotelResNotifRQHotelReservations() {
        return new OTAHotelResNotifRQ.HotelReservations();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRQ.HotelReservations.HotelReservation }
     * 
     */
    public OTAHotelResNotifRQ.HotelReservations.HotelReservation createOTAHotelResNotifRQHotelReservationsHotelReservation() {
        return new OTAHotelResNotifRQ.HotelReservations.HotelReservation();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGlobalInfo }
     * 
     */
    public OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGlobalInfo createOTAHotelResNotifRQHotelReservationsHotelReservationResGlobalInfo() {
        return new OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGlobalInfo();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGlobalInfo.Profiles }
     * 
     */
    public OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGlobalInfo.Profiles createOTAHotelResNotifRQHotelReservationsHotelReservationResGlobalInfoProfiles() {
        return new OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGlobalInfo.Profiles();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGlobalInfo.Profiles.ProfileInfo }
     * 
     */
    public OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGlobalInfo.Profiles.ProfileInfo createOTAHotelResNotifRQHotelReservationsHotelReservationResGlobalInfoProfilesProfileInfo() {
        return new OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGlobalInfo.Profiles.ProfileInfo();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGlobalInfo.Profiles.ProfileInfo.Profile }
     * 
     */
    public OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGlobalInfo.Profiles.ProfileInfo.Profile createOTAHotelResNotifRQHotelReservationsHotelReservationResGlobalInfoProfilesProfileInfoProfile() {
        return new OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGlobalInfo.Profiles.ProfileInfo.Profile();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGlobalInfo.Profiles.ProfileInfo.Profile.Customer }
     * 
     */
    public OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGlobalInfo.Profiles.ProfileInfo.Profile.Customer createOTAHotelResNotifRQHotelReservationsHotelReservationResGlobalInfoProfilesProfileInfoProfileCustomer() {
        return new OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGlobalInfo.Profiles.ProfileInfo.Profile.Customer();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGlobalInfo.HotelReservationIDs }
     * 
     */
    public OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGlobalInfo.HotelReservationIDs createOTAHotelResNotifRQHotelReservationsHotelReservationResGlobalInfoHotelReservationIDs() {
        return new OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGlobalInfo.HotelReservationIDs();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGlobalInfo.Total }
     * 
     */
    public OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGlobalInfo.Total createOTAHotelResNotifRQHotelReservationsHotelReservationResGlobalInfoTotal() {
        return new OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGlobalInfo.Total();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGlobalInfo.Total.Taxes }
     * 
     */
    public OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGlobalInfo.Total.Taxes createOTAHotelResNotifRQHotelReservationsHotelReservationResGlobalInfoTotalTaxes() {
        return new OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGlobalInfo.Total.Taxes();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGlobalInfo.Total.Taxes.Tax }
     * 
     */
    public OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGlobalInfo.Total.Taxes.Tax createOTAHotelResNotifRQHotelReservationsHotelReservationResGlobalInfoTotalTaxesTax() {
        return new OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGlobalInfo.Total.Taxes.Tax();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGlobalInfo.Comments }
     * 
     */
    public OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGlobalInfo.Comments createOTAHotelResNotifRQHotelReservationsHotelReservationResGlobalInfoComments() {
        return new OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGlobalInfo.Comments();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGuests }
     * 
     */
    public OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGuests createOTAHotelResNotifRQHotelReservationsHotelReservationResGuests() {
        return new OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGuests();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGuests.ResGuest }
     * 
     */
    public OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGuests.ResGuest createOTAHotelResNotifRQHotelReservationsHotelReservationResGuestsResGuest() {
        return new OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGuests.ResGuest();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGuests.ResGuest.Profiles }
     * 
     */
    public OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGuests.ResGuest.Profiles createOTAHotelResNotifRQHotelReservationsHotelReservationResGuestsResGuestProfiles() {
        return new OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGuests.ResGuest.Profiles();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGuests.ResGuest.Profiles.ProfileInfo }
     * 
     */
    public OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGuests.ResGuest.Profiles.ProfileInfo createOTAHotelResNotifRQHotelReservationsHotelReservationResGuestsResGuestProfilesProfileInfo() {
        return new OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGuests.ResGuest.Profiles.ProfileInfo();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGuests.ResGuest.Profiles.ProfileInfo.Profile }
     * 
     */
    public OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGuests.ResGuest.Profiles.ProfileInfo.Profile createOTAHotelResNotifRQHotelReservationsHotelReservationResGuestsResGuestProfilesProfileInfoProfile() {
        return new OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGuests.ResGuest.Profiles.ProfileInfo.Profile();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGuests.ResGuest.Profiles.ProfileInfo.Profile.Customer }
     * 
     */
    public OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGuests.ResGuest.Profiles.ProfileInfo.Profile.Customer createOTAHotelResNotifRQHotelReservationsHotelReservationResGuestsResGuestProfilesProfileInfoProfileCustomer() {
        return new OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGuests.ResGuest.Profiles.ProfileInfo.Profile.Customer();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRQ.HotelReservations.HotelReservation.RoomStays }
     * 
     */
    public OTAHotelResNotifRQ.HotelReservations.HotelReservation.RoomStays createOTAHotelResNotifRQHotelReservationsHotelReservationRoomStays() {
        return new OTAHotelResNotifRQ.HotelReservations.HotelReservation.RoomStays();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRQ.HotelReservations.HotelReservation.RoomStays.RoomStay }
     * 
     */
    public OTAHotelResNotifRQ.HotelReservations.HotelReservation.RoomStays.RoomStay createOTAHotelResNotifRQHotelReservationsHotelReservationRoomStaysRoomStay() {
        return new OTAHotelResNotifRQ.HotelReservations.HotelReservation.RoomStays.RoomStay();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRQ.HotelReservations.HotelReservation.RoomStays.RoomStay.ResGuestRPHs }
     * 
     */
    public OTAHotelResNotifRQ.HotelReservations.HotelReservation.RoomStays.RoomStay.ResGuestRPHs createOTAHotelResNotifRQHotelReservationsHotelReservationRoomStaysRoomStayResGuestRPHs() {
        return new OTAHotelResNotifRQ.HotelReservations.HotelReservation.RoomStays.RoomStay.ResGuestRPHs();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRQ.HotelReservations.HotelReservation.RoomStays.RoomStay.GuestCounts }
     * 
     */
    public OTAHotelResNotifRQ.HotelReservations.HotelReservation.RoomStays.RoomStay.GuestCounts createOTAHotelResNotifRQHotelReservationsHotelReservationRoomStaysRoomStayGuestCounts() {
        return new OTAHotelResNotifRQ.HotelReservations.HotelReservation.RoomStays.RoomStay.GuestCounts();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRQ.HotelReservations.HotelReservation.RoomStays.RoomStay.RoomRates }
     * 
     */
    public OTAHotelResNotifRQ.HotelReservations.HotelReservation.RoomStays.RoomStay.RoomRates createOTAHotelResNotifRQHotelReservationsHotelReservationRoomStaysRoomStayRoomRates() {
        return new OTAHotelResNotifRQ.HotelReservations.HotelReservation.RoomStays.RoomStay.RoomRates();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRQ.HotelReservations.HotelReservation.RoomStays.RoomStay.RoomRates.RoomRate }
     * 
     */
    public OTAHotelResNotifRQ.HotelReservations.HotelReservation.RoomStays.RoomStay.RoomRates.RoomRate createOTAHotelResNotifRQHotelReservationsHotelReservationRoomStaysRoomStayRoomRatesRoomRate() {
        return new OTAHotelResNotifRQ.HotelReservations.HotelReservation.RoomStays.RoomStay.RoomRates.RoomRate();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRQ.HotelReservations.HotelReservation.RoomStays.RoomStay.RoomRates.RoomRate.Rates }
     * 
     */
    public OTAHotelResNotifRQ.HotelReservations.HotelReservation.RoomStays.RoomStay.RoomRates.RoomRate.Rates createOTAHotelResNotifRQHotelReservationsHotelReservationRoomStaysRoomStayRoomRatesRoomRateRates() {
        return new OTAHotelResNotifRQ.HotelReservations.HotelReservation.RoomStays.RoomStay.RoomRates.RoomRate.Rates();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRQ.HotelReservations.HotelReservation.RoomStays.RoomStay.RoomRates.RoomRate.Rates.Rate }
     * 
     */
    public OTAHotelResNotifRQ.HotelReservations.HotelReservation.RoomStays.RoomStay.RoomRates.RoomRate.Rates.Rate createOTAHotelResNotifRQHotelReservationsHotelReservationRoomStaysRoomStayRoomRatesRoomRateRatesRate() {
        return new OTAHotelResNotifRQ.HotelReservations.HotelReservation.RoomStays.RoomStay.RoomRates.RoomRate.Rates.Rate();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRQ.HotelReservations.HotelReservation.RoomStays.RoomStay.RatePlans }
     * 
     */
    public OTAHotelResNotifRQ.HotelReservations.HotelReservation.RoomStays.RoomStay.RatePlans createOTAHotelResNotifRQHotelReservationsHotelReservationRoomStaysRoomStayRatePlans() {
        return new OTAHotelResNotifRQ.HotelReservations.HotelReservation.RoomStays.RoomStay.RatePlans();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRQ.HotelReservations.HotelReservation.RoomStays.RoomStay.RatePlans.RatePlan }
     * 
     */
    public OTAHotelResNotifRQ.HotelReservations.HotelReservation.RoomStays.RoomStay.RatePlans.RatePlan createOTAHotelResNotifRQHotelReservationsHotelReservationRoomStaysRoomStayRatePlansRatePlan() {
        return new OTAHotelResNotifRQ.HotelReservations.HotelReservation.RoomStays.RoomStay.RatePlans.RatePlan();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRQ.HotelReservations.HotelReservation.RoomStays.RoomStay.RoomTypes }
     * 
     */
    public OTAHotelResNotifRQ.HotelReservations.HotelReservation.RoomStays.RoomStay.RoomTypes createOTAHotelResNotifRQHotelReservationsHotelReservationRoomStaysRoomStayRoomTypes() {
        return new OTAHotelResNotifRQ.HotelReservations.HotelReservation.RoomStays.RoomStay.RoomTypes();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRQ.HotelReservations.HotelReservation.RoomStays.RoomStay.RoomTypes.RoomType }
     * 
     */
    public OTAHotelResNotifRQ.HotelReservations.HotelReservation.RoomStays.RoomStay.RoomTypes.RoomType createOTAHotelResNotifRQHotelReservationsHotelReservationRoomStaysRoomStayRoomTypesRoomType() {
        return new OTAHotelResNotifRQ.HotelReservations.HotelReservation.RoomStays.RoomStay.RoomTypes.RoomType();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRQ.HotelReservations.HotelReservation.POS }
     * 
     */
    public OTAHotelResNotifRQ.HotelReservations.HotelReservation.POS createOTAHotelResNotifRQHotelReservationsHotelReservationPOS() {
        return new OTAHotelResNotifRQ.HotelReservations.HotelReservation.POS();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRQ.HotelReservations.HotelReservation.POS.Source }
     * 
     */
    public OTAHotelResNotifRQ.HotelReservations.HotelReservation.POS.Source createOTAHotelResNotifRQHotelReservationsHotelReservationPOSSource() {
        return new OTAHotelResNotifRQ.HotelReservations.HotelReservation.POS.Source();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRS.HotelReservations.HotelReservation.UniqueID }
     * 
     */
    public OTAHotelResNotifRS.HotelReservations.HotelReservation.UniqueID createOTAHotelResNotifRSHotelReservationsHotelReservationUniqueID() {
        return new OTAHotelResNotifRS.HotelReservations.HotelReservation.UniqueID();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRS.HotelReservations.HotelReservation.ResGlobalInfo.HotelReservationIDs.HotelReservationID }
     * 
     */
    public OTAHotelResNotifRS.HotelReservations.HotelReservation.ResGlobalInfo.HotelReservationIDs.HotelReservationID createOTAHotelResNotifRSHotelReservationsHotelReservationResGlobalInfoHotelReservationIDsHotelReservationID() {
        return new OTAHotelResNotifRS.HotelReservations.HotelReservation.ResGlobalInfo.HotelReservationIDs.HotelReservationID();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRQ.HotelReservations.HotelReservation.UniqueID }
     * 
     */
    public OTAHotelResNotifRQ.HotelReservations.HotelReservation.UniqueID createOTAHotelResNotifRQHotelReservationsHotelReservationUniqueID() {
        return new OTAHotelResNotifRQ.HotelReservations.HotelReservation.UniqueID();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGlobalInfo.TimeSpan }
     * 
     */
    public OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGlobalInfo.TimeSpan createOTAHotelResNotifRQHotelReservationsHotelReservationResGlobalInfoTimeSpan() {
        return new OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGlobalInfo.TimeSpan();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGlobalInfo.BasicPropertyInfo }
     * 
     */
    public OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGlobalInfo.BasicPropertyInfo createOTAHotelResNotifRQHotelReservationsHotelReservationResGlobalInfoBasicPropertyInfo() {
        return new OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGlobalInfo.BasicPropertyInfo();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGlobalInfo.Profiles.ProfileInfo.Profile.Customer.PersonName }
     * 
     */
    public OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGlobalInfo.Profiles.ProfileInfo.Profile.Customer.PersonName createOTAHotelResNotifRQHotelReservationsHotelReservationResGlobalInfoProfilesProfileInfoProfileCustomerPersonName() {
        return new OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGlobalInfo.Profiles.ProfileInfo.Profile.Customer.PersonName();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGlobalInfo.Profiles.ProfileInfo.Profile.Customer.Telephone }
     * 
     */
    public OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGlobalInfo.Profiles.ProfileInfo.Profile.Customer.Telephone createOTAHotelResNotifRQHotelReservationsHotelReservationResGlobalInfoProfilesProfileInfoProfileCustomerTelephone() {
        return new OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGlobalInfo.Profiles.ProfileInfo.Profile.Customer.Telephone();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGlobalInfo.Profiles.ProfileInfo.Profile.Customer.Email }
     * 
     */
    public OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGlobalInfo.Profiles.ProfileInfo.Profile.Customer.Email createOTAHotelResNotifRQHotelReservationsHotelReservationResGlobalInfoProfilesProfileInfoProfileCustomerEmail() {
        return new OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGlobalInfo.Profiles.ProfileInfo.Profile.Customer.Email();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGlobalInfo.Profiles.ProfileInfo.Profile.Customer.Address }
     * 
     */
    public OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGlobalInfo.Profiles.ProfileInfo.Profile.Customer.Address createOTAHotelResNotifRQHotelReservationsHotelReservationResGlobalInfoProfilesProfileInfoProfileCustomerAddress() {
        return new OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGlobalInfo.Profiles.ProfileInfo.Profile.Customer.Address();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGlobalInfo.HotelReservationIDs.HotelReservationID }
     * 
     */
    public OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGlobalInfo.HotelReservationIDs.HotelReservationID createOTAHotelResNotifRQHotelReservationsHotelReservationResGlobalInfoHotelReservationIDsHotelReservationID() {
        return new OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGlobalInfo.HotelReservationIDs.HotelReservationID();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGlobalInfo.Total.Taxes.Tax.TaxDescription }
     * 
     */
    public OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGlobalInfo.Total.Taxes.Tax.TaxDescription createOTAHotelResNotifRQHotelReservationsHotelReservationResGlobalInfoTotalTaxesTaxTaxDescription() {
        return new OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGlobalInfo.Total.Taxes.Tax.TaxDescription();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGlobalInfo.Comments.Comment }
     * 
     */
    public OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGlobalInfo.Comments.Comment createOTAHotelResNotifRQHotelReservationsHotelReservationResGlobalInfoCommentsComment() {
        return new OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGlobalInfo.Comments.Comment();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGuests.ResGuest.Profiles.ProfileInfo.Profile.Customer.PersonName }
     * 
     */
    public OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGuests.ResGuest.Profiles.ProfileInfo.Profile.Customer.PersonName createOTAHotelResNotifRQHotelReservationsHotelReservationResGuestsResGuestProfilesProfileInfoProfileCustomerPersonName() {
        return new OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGuests.ResGuest.Profiles.ProfileInfo.Profile.Customer.PersonName();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGuests.ResGuest.Profiles.ProfileInfo.Profile.Customer.Telephone }
     * 
     */
    public OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGuests.ResGuest.Profiles.ProfileInfo.Profile.Customer.Telephone createOTAHotelResNotifRQHotelReservationsHotelReservationResGuestsResGuestProfilesProfileInfoProfileCustomerTelephone() {
        return new OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGuests.ResGuest.Profiles.ProfileInfo.Profile.Customer.Telephone();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGuests.ResGuest.Profiles.ProfileInfo.Profile.Customer.Email }
     * 
     */
    public OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGuests.ResGuest.Profiles.ProfileInfo.Profile.Customer.Email createOTAHotelResNotifRQHotelReservationsHotelReservationResGuestsResGuestProfilesProfileInfoProfileCustomerEmail() {
        return new OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGuests.ResGuest.Profiles.ProfileInfo.Profile.Customer.Email();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGuests.ResGuest.Profiles.ProfileInfo.Profile.Customer.Address }
     * 
     */
    public OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGuests.ResGuest.Profiles.ProfileInfo.Profile.Customer.Address createOTAHotelResNotifRQHotelReservationsHotelReservationResGuestsResGuestProfilesProfileInfoProfileCustomerAddress() {
        return new OTAHotelResNotifRQ.HotelReservations.HotelReservation.ResGuests.ResGuest.Profiles.ProfileInfo.Profile.Customer.Address();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRQ.HotelReservations.HotelReservation.RoomStays.RoomStay.TimeSpan }
     * 
     */
    public OTAHotelResNotifRQ.HotelReservations.HotelReservation.RoomStays.RoomStay.TimeSpan createOTAHotelResNotifRQHotelReservationsHotelReservationRoomStaysRoomStayTimeSpan() {
        return new OTAHotelResNotifRQ.HotelReservations.HotelReservation.RoomStays.RoomStay.TimeSpan();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRQ.HotelReservations.HotelReservation.RoomStays.RoomStay.Total }
     * 
     */
    public OTAHotelResNotifRQ.HotelReservations.HotelReservation.RoomStays.RoomStay.Total createOTAHotelResNotifRQHotelReservationsHotelReservationRoomStaysRoomStayTotal() {
        return new OTAHotelResNotifRQ.HotelReservations.HotelReservation.RoomStays.RoomStay.Total();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRQ.HotelReservations.HotelReservation.RoomStays.RoomStay.ResGuestRPHs.ResGuestRPH }
     * 
     */
    public OTAHotelResNotifRQ.HotelReservations.HotelReservation.RoomStays.RoomStay.ResGuestRPHs.ResGuestRPH createOTAHotelResNotifRQHotelReservationsHotelReservationRoomStaysRoomStayResGuestRPHsResGuestRPH() {
        return new OTAHotelResNotifRQ.HotelReservations.HotelReservation.RoomStays.RoomStay.ResGuestRPHs.ResGuestRPH();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRQ.HotelReservations.HotelReservation.RoomStays.RoomStay.GuestCounts.GuestCount }
     * 
     */
    public OTAHotelResNotifRQ.HotelReservations.HotelReservation.RoomStays.RoomStay.GuestCounts.GuestCount createOTAHotelResNotifRQHotelReservationsHotelReservationRoomStaysRoomStayGuestCountsGuestCount() {
        return new OTAHotelResNotifRQ.HotelReservations.HotelReservation.RoomStays.RoomStay.GuestCounts.GuestCount();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRQ.HotelReservations.HotelReservation.RoomStays.RoomStay.RoomRates.RoomRate.Rates.Rate.Base }
     * 
     */
    public OTAHotelResNotifRQ.HotelReservations.HotelReservation.RoomStays.RoomStay.RoomRates.RoomRate.Rates.Rate.Base createOTAHotelResNotifRQHotelReservationsHotelReservationRoomStaysRoomStayRoomRatesRoomRateRatesRateBase() {
        return new OTAHotelResNotifRQ.HotelReservations.HotelReservation.RoomStays.RoomStay.RoomRates.RoomRate.Rates.Rate.Base();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRQ.HotelReservations.HotelReservation.RoomStays.RoomStay.RoomRates.RoomRate.Rates.Rate.Total }
     * 
     */
    public OTAHotelResNotifRQ.HotelReservations.HotelReservation.RoomStays.RoomStay.RoomRates.RoomRate.Rates.Rate.Total createOTAHotelResNotifRQHotelReservationsHotelReservationRoomStaysRoomStayRoomRatesRoomRateRatesRateTotal() {
        return new OTAHotelResNotifRQ.HotelReservations.HotelReservation.RoomStays.RoomStay.RoomRates.RoomRate.Rates.Rate.Total();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRQ.HotelReservations.HotelReservation.RoomStays.RoomStay.RatePlans.RatePlan.RatePlanDescription }
     * 
     */
    public OTAHotelResNotifRQ.HotelReservations.HotelReservation.RoomStays.RoomStay.RatePlans.RatePlan.RatePlanDescription createOTAHotelResNotifRQHotelReservationsHotelReservationRoomStaysRoomStayRatePlansRatePlanRatePlanDescription() {
        return new OTAHotelResNotifRQ.HotelReservations.HotelReservation.RoomStays.RoomStay.RatePlans.RatePlan.RatePlanDescription();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRQ.HotelReservations.HotelReservation.RoomStays.RoomStay.RoomTypes.RoomType.RoomDescription }
     * 
     */
    public OTAHotelResNotifRQ.HotelReservations.HotelReservation.RoomStays.RoomStay.RoomTypes.RoomType.RoomDescription createOTAHotelResNotifRQHotelReservationsHotelReservationRoomStaysRoomStayRoomTypesRoomTypeRoomDescription() {
        return new OTAHotelResNotifRQ.HotelReservations.HotelReservation.RoomStays.RoomStay.RoomTypes.RoomType.RoomDescription();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRQ.HotelReservations.HotelReservation.POS.Source.RequestorID }
     * 
     */
    public OTAHotelResNotifRQ.HotelReservations.HotelReservation.POS.Source.RequestorID createOTAHotelResNotifRQHotelReservationsHotelReservationPOSSourceRequestorID() {
        return new OTAHotelResNotifRQ.HotelReservations.HotelReservation.POS.Source.RequestorID();
    }

    /**
     * Create an instance of {@link OTAHotelResNotifRQ.HotelReservations.HotelReservation.POS.Source.BookingChannel }
     * 
     */
    public OTAHotelResNotifRQ.HotelReservations.HotelReservation.POS.Source.BookingChannel createOTAHotelResNotifRQHotelReservationsHotelReservationPOSSourceBookingChannel() {
        return new OTAHotelResNotifRQ.HotelReservations.HotelReservation.POS.Source.BookingChannel();
    }

}
