//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.15 at 10:56:07 AM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.iunona-trip.com/soapproducer/reservation/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.iunona_trip.soapproducer.reservation;
